version: '3.4'

services:
  catalog-api:
    container_name: catalog-api
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: ./src/Catalog.Api/Dockerfile
    ports:
      - '5000:80'
      - '5001:443'
    environment:
      - 'ASPNETCORE_ENVIRONMENT=Development'
      
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
      
volumes:
  mongo: