version: '3.4'

services:
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: ./src/Catalog.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    networks:
      - local

networks:
  local:
    driver: bridge